# Generated by Django 5.2.13 on 2026-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.'), ('Adv', 'Adv.')], default='Mr', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('alternate_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('voter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(default='India', max_length=50)),
                ('residence_type', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented'), ('Leased', 'Leased'), ('Parental', 'Parental')], default='Owned', max_length=20)),
                ('occupation', models.CharField(choices=[('salaried', 'Salaried Employee'), ('self_employed', 'Self Employed'), ('business', 'Business Owner'), ('student', 'Student'), ('retired', 'Retired'), ('homemaker', 'Home Maker'), ('other', 'Other')], max_length=50)),
                ('income_range', models.CharField(choices=[('0-25000', '₹0 - ₹25,000'), ('25001-50000', '₹25,001 - ₹50,000'), ('50001-100000', '₹50,001 - ₹1,00,000'), ('100001-200000', '₹1,00,001 - ₹2,00,000'), ('200001-500000', '₹2,00,001 - ₹5,00,000'), ('500001+', '₹5,00,001+')], max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('salary', 'Salary Account'), ('fixed', 'Fixed Deposit Account'), ('nri', 'NRI Account')], default='savings', max_length=20)),
                ('nomination_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nomination_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_card_image', models.FileField(blank=True, null=True, upload_to='documents/pan/')),
                ('aadhaar_front_image', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('aadhaar_back_image', models.FileField(blank=True, null=True, upload_to='documents/aadhaar/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='documents/photos/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='documents/signatures/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='documents/address/')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='documents/income/')),
                ('nomineename', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_dob', models.DateField(blank=True, null=True)),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_kyc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(default='pending', max_length=20)),
                ('application_id', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
