# Generated by Django 5.2.13 on 2026-04-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankapplication',
            name='aadhaar_back_image',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='agree_kyc',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='income_proof',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='landline',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='nomination_name',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='nominee_relation',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='nomineename',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='residence_type',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='signature_image',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='bankapplication',
            name='nominee_name',
            field=models.CharField(default='Test User', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='aadhaar_front_image',
            field=models.FileField(default='documents/aadhaar/default.png', upload_to='documents/aadhaar/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='aadhaar_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='account_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='income_range',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='nomination_relation',
            field=models.CharField(default='Father', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='nominee_dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='occupation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='pan_card_image',
            field=models.FileField(upload_to='documents/pan/'),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='pan_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='passport_photo',
            field=models.ImageField(default='documents/photos/default.png', upload_to='documents/photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='voter_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
