# Generated by Django 5.2.13 on 2026-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_remove_bankapplication_aadhaar_back_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankapplication',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='alternate_mobile',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='bankapplication',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='bankapplication',
            name='driving_license',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='aadhaar_front_image',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='address_line1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='income_range',
            field=models.CharField(choices=[('Below 1 Lakh', 'Below 1 Lakh'), ('1-5 Lakh', '1-5 Lakh'), ('Above 5 Lakh', 'Above 5 Lakh')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='nominee_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='pan_card_image',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='passport_photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankapplication',
            name='voter_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
