# Generated by Django 5.2.13 on 2026-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_rename_created_at_bankapplication_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankapplication',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
