# Generated by Django 5.2.13 on 2026-04-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_bankapplication_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankapplication',
            old_name='address_line1',
            new_name='address_line',
        ),
    ]
