# Generated by Django 5.2.13 on 2026-04-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_rename_address_line1_bankapplication_address_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankapplication',
            old_name='aadhaar_front_image',
            new_name='aadhaar_card',
        ),
        migrations.AddField(
            model_name='bankapplication',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
